name: editor_build
version: 0.0.2
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: This package allows a simple interaction with Dart Editor in build.dart
homepage: https://github.com/a14n/dart-editor-build
dependencies:
  args: any
dev_dependencies:
  unittest: any
