name: editor_build
version: 0.0.5-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to interact with Dart Editor in build.dart
homepage: https://github.com/a14n/dart-editor-build
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.13.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
