name: editor_build
version: 0.0.4-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to interact with Dart Editor in build.dart
homepage: https://github.com/a14n/dart-editor-build
dependencies:
  args: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
